using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

[CreateAssetMenu(menuName = "Create Sound Factory", fileName = "SoundFactory")]
public class SoundFactory : ScriptableObject    
{
    public List<Music_SFX> musicList = new List<Music_SFX>();
    public List<Sound_SFX> sfxList = new List<Sound_SFX>();

    [System.Serializable]
    public class Sound_SFX
    {
        public SoundManager.SFX sfx;
        public float timer;
        public float timeToDespawn;
        public AudioClip audioClip;
    }

    [System.Serializable]
    public class Music_SFX
    {
        public SoundManager.Music music;
        public AudioClip audioClip;
    }
}

public static class GenerateSFXEnumFromFactory
{
    private const string OUTPUT_PATH = "Assets/Scripts/Sounds/GeneratedSFX.cs";

    [MenuItem("Tools/Audio/Generate SFX Enum from SoundFactory")]
    public static void Generate()
    {
        var guids = AssetDatabase.FindAssets("t:SoundFactory");
        if (guids == null || guids.Length == 0)
        {
            Debug.LogError("[GenerateSFXEnum] No SoundFactory asset found in project.");
            return;
        }

        // Use the first SoundFactory found
        var path = AssetDatabase.GUIDToAssetPath(guids[0]);
        var factory = AssetDatabase.LoadAssetAtPath<SoundFactory>(path);
        if (factory == null)
        {
            Debug.LogError("[GenerateSFXEnum] Failed to load SoundFactory at " + path);
            return;
        }

        var rawNames = new List<string>();
        foreach (var entry in factory.sfxList)
        {
            string name = null;
            if (entry == null) continue;

            if (entry.audioClip != null && !string.IsNullOrEmpty(entry.audioClip.name))
                name = entry.audioClip.name;
            else if (!string.IsNullOrEmpty(entry.sfx.ToString()))
                name = entry.sfx.ToString();
            else
                name = "UnnamedSFX";

            rawNames.Add(name);
        }

        if (rawNames.Count == 0)
        {
            Debug.LogWarning("[GenerateSFXEnum] No SFX entries found in SoundFactory.");
            return;
        }

        // sanitize and make unique
        var names = new List<string>();
        var used = new HashSet<string>();
        for (int i = 0; i < rawNames.Count; i++)
        {
            string sanitized = SanitizeIdentifier(rawNames[i]);
            string candidate = sanitized;
            int suffix = 1;
            while (used.Contains(candidate))
            {
                candidate = sanitized + "_" + suffix++;
            }
            used.Add(candidate);
            names.Add(candidate);
        }

        // Build enum file content
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by GenerateSFXEnumFromFactory. Do not edit manually.");
        sb.AppendLine("// Regenerate via __Tools > Audio > Generate SFX Enum from SoundFactory__");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("public partial class SoundManager");
        sb.AppendLine("{");
        sb.AppendLine("    public enum SFX");
        sb.AppendLine("    {");
        sb.AppendLine("        NULL,");
        foreach (var n in names)
            sb.AppendLine("        " + n + ",");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Ensure output folder exists
        Directory.CreateDirectory(Path.GetDirectoryName(OUTPUT_PATH));

        File.WriteAllText(OUTPUT_PATH, sb.ToString(), Encoding.UTF8);
        AssetDatabase.Refresh();

        Debug.Log("[GenerateSFXEnum] Generated SFX enum with " + names.Count + " entries -> " + OUTPUT_PATH);
    }

    private static string SanitizeIdentifier(string input)
    {
        if (string.IsNullOrEmpty(input)) return "SFX_Unknown";

        var sb = new StringBuilder();
        foreach (char c in input)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }

        // ensure it doesn't start with a digit
        string outStr = sb.ToString();
        if (char.IsDigit(outStr[0]))
            outStr = "_" + outStr;

        // collapse consecutive underscores
        while (outStr.Contains("__"))
            outStr = outStr.Replace("__", "_");

        return outStr;
    }
}
